project:
  type: website
  
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
  
website:
  title: "Olivia Shaw"
  description: "Personal website of Olivia Shaw"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      #- href: "research/index.qmd"
      #- text: "Research"
      - href: research.qmd
        text: Research
      - href: cv1/CV updated copy 10-16-23.pdf
        text: CV
format: 
  html:
    theme: Lux
    toc: true
  
  
  